// Mock数据存储
const MockData = {
    users: [
        { userId: 1, username: 'admin', realName: '人事经理1', role: 'HR_MANAGER', email: 'admin@example.com', phone: '13800000001', status: 'ACTIVE' },
        { userId: 2, username: 'hr01', realName: '人事专员', role: 'HR_SPECIALIST', email: 'hr01@example.com', phone: '13800138001', status: 'ACTIVE' },
        { userId: 3, username: 'hr02', realName: '人事经理2', role: 'HR_MANAGER', email: 'hr02@example.com', phone: '13800138002', status: 'ACTIVE' },
        { userId: 4, username: 'salary01', realName: '薪酬专员', role: 'SALARY_SPECIALIST', email: 'salary01@example.com', phone: '13800138003', status: 'ACTIVE' },
        { userId: 5, username: 'salary02', realName: '薪酬经理', role: 'SALARY_MANAGER', email: 'salary02@example.com', phone: '13800138004', status: 'ACTIVE' }
    ],
    organizations: [
        // 一级机构
        { orgId: 1, orgCode: '01', orgName: '技术中心', orgLevel: 1, parentId: null, status: 'ACTIVE' },
        { orgId: 2, orgCode: '02', orgName: '市场中心', orgLevel: 1, parentId: null, status: 'ACTIVE' },
        { orgId: 3, orgCode: '03', orgName: '人力资源中心', orgLevel: 1, parentId: null, status: 'ACTIVE' },
        { orgId: 4, orgCode: '04', orgName: '财务中心', orgLevel: 1, parentId: null, status: 'ACTIVE' },
        { orgId: 5, orgCode: '05', orgName: '运营中心', orgLevel: 1, parentId: null, status: 'ACTIVE' },
        
        // 二级机构 - 技术中心下
        { orgId: 10, orgCode: '01', orgName: '产品研发部', orgLevel: 2, parentId: 1, status: 'ACTIVE' },
        { orgId: 11, orgCode: '02', orgName: '测试部', orgLevel: 2, parentId: 1, status: 'ACTIVE' },
        { orgId: 12, orgCode: '03', orgName: '技术架构部', orgLevel: 2, parentId: 1, status: 'ACTIVE' },
        { orgId: 13, orgCode: '04', orgName: '运维部', orgLevel: 2, parentId: 1, status: 'ACTIVE' },
        
        // 二级机构 - 市场中心下
        { orgId: 20, orgCode: '01', orgName: '市场推广部', orgLevel: 2, parentId: 2, status: 'ACTIVE' },
        { orgId: 21, orgCode: '02', orgName: '品牌营销部', orgLevel: 2, parentId: 2, status: 'ACTIVE' },
        { orgId: 22, orgCode: '03', orgName: '渠道拓展部', orgLevel: 2, parentId: 2, status: 'ACTIVE' },
        
        // 二级机构 - 人力资源中心下
        { orgId: 30, orgCode: '01', orgName: '招聘部', orgLevel: 2, parentId: 3, status: 'ACTIVE' },
        { orgId: 31, orgCode: '02', orgName: '培训部', orgLevel: 2, parentId: 3, status: 'ACTIVE' },
        { orgId: 32, orgCode: '03', orgName: '薪酬绩效部', orgLevel: 2, parentId: 3, status: 'ACTIVE' },
        
        // 二级机构 - 财务中心下
        { orgId: 40, orgCode: '01', orgName: '会计部', orgLevel: 2, parentId: 4, status: 'ACTIVE' },
        { orgId: 41, orgCode: '02', orgName: '审计部', orgLevel: 2, parentId: 4, status: 'ACTIVE' },
        
        // 二级机构 - 运营中心下
        { orgId: 50, orgCode: '01', orgName: '客户服务部', orgLevel: 2, parentId: 5, status: 'ACTIVE' },
        { orgId: 51, orgCode: '02', orgName: '数据分析部', orgLevel: 2, parentId: 5, status: 'ACTIVE' },
        
        // 三级机构 - 产品研发部下
        { orgId: 100, orgCode: '01', orgName: '前端组', orgLevel: 3, parentId: 10, status: 'ACTIVE' },
        { orgId: 101, orgCode: '02', orgName: '后端组', orgLevel: 3, parentId: 10, status: 'ACTIVE' },
        { orgId: 102, orgCode: '03', orgName: '移动端组', orgLevel: 3, parentId: 10, status: 'ACTIVE' },
        { orgId: 103, orgCode: '04', orgName: '算法组', orgLevel: 3, parentId: 10, status: 'ACTIVE' },
        
        // 三级机构 - 测试部下
        { orgId: 110, orgCode: '01', orgName: '功能测试组', orgLevel: 3, parentId: 11, status: 'ACTIVE' },
        { orgId: 111, orgCode: '02', orgName: '自动化测试组', orgLevel: 3, parentId: 11, status: 'ACTIVE' },
        { orgId: 112, orgCode: '03', orgName: '性能测试组', orgLevel: 3, parentId: 11, status: 'ACTIVE' },
        
        // 三级机构 - 技术架构部下
        { orgId: 120, orgCode: '01', orgName: '架构设计组', orgLevel: 3, parentId: 12, status: 'ACTIVE' },
        { orgId: 121, orgCode: '02', orgName: '技术研究组', orgLevel: 3, parentId: 12, status: 'ACTIVE' },
        
        // 三级机构 - 运维部下
        { orgId: 130, orgCode: '01', orgName: '系统运维组', orgLevel: 3, parentId: 13, status: 'ACTIVE' },
        { orgId: 131, orgCode: '02', orgName: '网络运维组', orgLevel: 3, parentId: 13, status: 'ACTIVE' },
        
        // 三级机构 - 市场推广部下
        { orgId: 200, orgCode: '01', orgName: '线上推广组', orgLevel: 3, parentId: 20, status: 'ACTIVE' },
        { orgId: 201, orgCode: '02', orgName: '线下推广组', orgLevel: 3, parentId: 20, status: 'ACTIVE' },
        
        // 三级机构 - 品牌营销部下
        { orgId: 210, orgCode: '01', orgName: '品牌策划组', orgLevel: 3, parentId: 21, status: 'ACTIVE' },
        { orgId: 211, orgCode: '02', orgName: '内容营销组', orgLevel: 3, parentId: 21, status: 'ACTIVE' },
        
        // 三级机构 - 渠道拓展部下
        { orgId: 220, orgCode: '01', orgName: '渠道开发组', orgLevel: 3, parentId: 22, status: 'ACTIVE' },
        { orgId: 221, orgCode: '02', orgName: '渠道维护组', orgLevel: 3, parentId: 22, status: 'ACTIVE' },
        
        // 三级机构 - 招聘部下
        { orgId: 300, orgCode: '01', orgName: '技术招聘组', orgLevel: 3, parentId: 30, status: 'ACTIVE' },
        { orgId: 301, orgCode: '02', orgName: '非技术招聘组', orgLevel: 3, parentId: 30, status: 'ACTIVE' },
        
        // 三级机构 - 培训部下
        { orgId: 310, orgCode: '01', orgName: '新员工培训组', orgLevel: 3, parentId: 31, status: 'ACTIVE' },
        { orgId: 311, orgCode: '02', orgName: '在职培训组', orgLevel: 3, parentId: 31, status: 'ACTIVE' },
        
        // 三级机构 - 薪酬绩效部下
        { orgId: 320, orgCode: '01', orgName: '薪酬管理组', orgLevel: 3, parentId: 32, status: 'ACTIVE' },
        { orgId: 321, orgCode: '02', orgName: '绩效管理组', orgLevel: 3, parentId: 32, status: 'ACTIVE' },
        
        // 三级机构 - 会计部下
        { orgId: 400, orgCode: '01', orgName: '财务会计组', orgLevel: 3, parentId: 40, status: 'ACTIVE' },
        { orgId: 401, orgCode: '02', orgName: '成本会计组', orgLevel: 3, parentId: 40, status: 'ACTIVE' },
        
        // 三级机构 - 审计部下
        { orgId: 410, orgCode: '01', orgName: '内部审计组', orgLevel: 3, parentId: 41, status: 'ACTIVE' },
        
        // 三级机构 - 客户服务部下
        { orgId: 500, orgCode: '01', orgName: '在线客服组', orgLevel: 3, parentId: 50, status: 'ACTIVE' },
        { orgId: 501, orgCode: '02', orgName: '电话客服组', orgLevel: 3, parentId: 50, status: 'ACTIVE' },
        
        // 三级机构 - 数据分析部下
        { orgId: 510, orgCode: '01', orgName: '数据挖掘组', orgLevel: 3, parentId: 51, status: 'ACTIVE' },
        { orgId: 511, orgCode: '02', orgName: '商业分析组', orgLevel: 3, parentId: 51, status: 'ACTIVE' }
    ],
    positions: [
        // 前端组职位
        { positionId: 1, positionName: '前端工程师', thirdOrgId: 100, description: '', status: 'ACTIVE' },
        { positionId: 2, positionName: '高级前端工程师', thirdOrgId: 100, description: '', status: 'ACTIVE' },
        { positionId: 3, positionName: '前端架构师', thirdOrgId: 100, description: '', status: 'ACTIVE' },
        { positionId: 4, positionName: '前端开发经理', thirdOrgId: 100, description: '', status: 'ACTIVE' },
        
        // 后端组职位
        { positionId: 10, positionName: '后端工程师', thirdOrgId: 101, description: '', status: 'ACTIVE' },
        { positionId: 11, positionName: '高级后端工程师', thirdOrgId: 101, description: '', status: 'ACTIVE' },
        { positionId: 12, positionName: '后端架构师', thirdOrgId: 101, description: '', status: 'ACTIVE' },
        { positionId: 13, positionName: '后端开发经理', thirdOrgId: 101, description: '', status: 'ACTIVE' },
        
        // 移动端组职位
        { positionId: 20, positionName: 'iOS开发工程师', thirdOrgId: 102, description: '', status: 'ACTIVE' },
        { positionId: 21, positionName: 'Android开发工程师', thirdOrgId: 102, description: '', status: 'ACTIVE' },
        { positionId: 22, positionName: '移动端开发经理', thirdOrgId: 102, description: '', status: 'ACTIVE' },
        
        // 算法组职位
        { positionId: 30, positionName: '算法工程师', thirdOrgId: 103, description: '', status: 'ACTIVE' },
        { positionId: 31, positionName: '高级算法工程师', thirdOrgId: 103, description: '', status: 'ACTIVE' },
        { positionId: 32, positionName: '算法专家', thirdOrgId: 103, description: '', status: 'ACTIVE' },
        
        // 功能测试组职位
        { positionId: 40, positionName: '测试工程师', thirdOrgId: 110, description: '', status: 'ACTIVE' },
        { positionId: 41, positionName: '高级测试工程师', thirdOrgId: 110, description: '', status: 'ACTIVE' },
        { positionId: 42, positionName: '测试经理', thirdOrgId: 110, description: '', status: 'ACTIVE' },
        
        // 自动化测试组职位
        { positionId: 50, positionName: '自动化测试工程师', thirdOrgId: 111, description: '', status: 'ACTIVE' },
        { positionId: 51, positionName: '测试开发工程师', thirdOrgId: 111, description: '', status: 'ACTIVE' },
        
        // 性能测试组职位
        { positionId: 60, positionName: '性能测试工程师', thirdOrgId: 112, description: '', status: 'ACTIVE' },
        { positionId: 61, positionName: '高级性能测试工程师', thirdOrgId: 112, description: '', status: 'ACTIVE' },
        
        // 架构设计组职位
        { positionId: 70, positionName: '系统架构师', thirdOrgId: 120, description: '', status: 'ACTIVE' },
        { positionId: 71, positionName: '技术专家', thirdOrgId: 120, description: '', status: 'ACTIVE' },
        { positionId: 72, positionName: '首席架构师', thirdOrgId: 120, description: '', status: 'ACTIVE' },
        
        // 技术研究组职位
        { positionId: 80, positionName: '技术研究员', thirdOrgId: 121, description: '', status: 'ACTIVE' },
        { positionId: 81, positionName: '高级技术研究员', thirdOrgId: 121, description: '', status: 'ACTIVE' },
        
        // 系统运维组职位
        { positionId: 90, positionName: '运维工程师', thirdOrgId: 130, description: '', status: 'ACTIVE' },
        { positionId: 91, positionName: '高级运维工程师', thirdOrgId: 130, description: '', status: 'ACTIVE' },
        { positionId: 92, positionName: '运维经理', thirdOrgId: 130, description: '', status: 'ACTIVE' },
        
        // 网络运维组职位
        { positionId: 100, positionName: '网络工程师', thirdOrgId: 131, description: '', status: 'ACTIVE' },
        { positionId: 101, positionName: '网络架构师', thirdOrgId: 131, description: '', status: 'ACTIVE' },
        
        // 线上推广组职位
        { positionId: 110, positionName: '线上推广专员', thirdOrgId: 200, description: '', status: 'ACTIVE' },
        { positionId: 111, positionName: 'SEM专员', thirdOrgId: 200, description: '', status: 'ACTIVE' },
        { positionId: 112, positionName: 'SEO专员', thirdOrgId: 200, description: '', status: 'ACTIVE' },
        { positionId: 113, positionName: '线上推广经理', thirdOrgId: 200, description: '', status: 'ACTIVE' },
        
        // 线下推广组职位
        { positionId: 120, positionName: '线下推广专员', thirdOrgId: 201, description: '', status: 'ACTIVE' },
        { positionId: 121, positionName: '渠道专员', thirdOrgId: 201, description: '', status: 'ACTIVE' },
        
        // 品牌策划组职位
        { positionId: 130, positionName: '品牌策划专员', thirdOrgId: 210, description: '', status: 'ACTIVE' },
        { positionId: 131, positionName: '品牌经理', thirdOrgId: 210, description: '', status: 'ACTIVE' },
        
        // 内容营销组职位
        { positionId: 140, positionName: '内容运营专员', thirdOrgId: 211, description: '', status: 'ACTIVE' },
        { positionId: 141, positionName: '新媒体运营', thirdOrgId: 211, description: '', status: 'ACTIVE' },
        { positionId: 142, positionName: '内容营销经理', thirdOrgId: 211, description: '', status: 'ACTIVE' },
        
        // 渠道开发组职位
        { positionId: 150, positionName: '渠道开发专员', thirdOrgId: 220, description: '', status: 'ACTIVE' },
        { positionId: 151, positionName: '渠道开发经理', thirdOrgId: 220, description: '', status: 'ACTIVE' },
        
        // 渠道维护组职位
        { positionId: 160, positionName: '渠道维护专员', thirdOrgId: 221, description: '', status: 'ACTIVE' },
        { positionId: 161, positionName: '渠道关系经理', thirdOrgId: 221, description: '', status: 'ACTIVE' },
        
        // 技术招聘组职位
        { positionId: 170, positionName: '技术招聘专员', thirdOrgId: 300, description: '', status: 'ACTIVE' },
        { positionId: 171, positionName: '高级招聘专员', thirdOrgId: 300, description: '', status: 'ACTIVE' },
        { positionId: 172, positionName: '招聘经理', thirdOrgId: 300, description: '', status: 'ACTIVE' },
        
        // 非技术招聘组职位
        { positionId: 180, positionName: '招聘专员', thirdOrgId: 301, description: '', status: 'ACTIVE' },
        { positionId: 181, positionName: '招聘主管', thirdOrgId: 301, description: '', status: 'ACTIVE' },
        
        // 新员工培训组职位
        { positionId: 190, positionName: '培训专员', thirdOrgId: 310, description: '', status: 'ACTIVE' },
        { positionId: 191, positionName: '培训经理', thirdOrgId: 310, description: '', status: 'ACTIVE' },
        
        // 在职培训组职位
        { positionId: 200, positionName: '培训讲师', thirdOrgId: 311, description: '', status: 'ACTIVE' },
        { positionId: 201, positionName: '高级培训讲师', thirdOrgId: 311, description: '', status: 'ACTIVE' },
        
        // 薪酬管理组职位
        { positionId: 210, positionName: '薪酬专员', thirdOrgId: 320, description: '', status: 'ACTIVE' },
        { positionId: 211, positionName: '薪酬经理', thirdOrgId: 320, description: '', status: 'ACTIVE' },
        
        // 绩效管理组职位
        { positionId: 220, positionName: '绩效专员', thirdOrgId: 321, description: '', status: 'ACTIVE' },
        { positionId: 221, positionName: '绩效经理', thirdOrgId: 321, description: '', status: 'ACTIVE' },
        
        // 财务会计组职位
        { positionId: 230, positionName: '会计', thirdOrgId: 400, description: '', status: 'ACTIVE' },
        { positionId: 231, positionName: '高级会计', thirdOrgId: 400, description: '', status: 'ACTIVE' },
        { positionId: 232, positionName: '财务经理', thirdOrgId: 400, description: '', status: 'ACTIVE' },
        
        // 成本会计组职位
        { positionId: 240, positionName: '成本会计', thirdOrgId: 401, description: '', status: 'ACTIVE' },
        { positionId: 241, positionName: '成本会计经理', thirdOrgId: 401, description: '', status: 'ACTIVE' },
        
        // 内部审计组职位
        { positionId: 250, positionName: '审计专员', thirdOrgId: 410, description: '', status: 'ACTIVE' },
        { positionId: 251, positionName: '审计经理', thirdOrgId: 410, description: '', status: 'ACTIVE' },
        
        // 在线客服组职位
        { positionId: 260, positionName: '在线客服', thirdOrgId: 500, description: '', status: 'ACTIVE' },
        { positionId: 261, positionName: '客服主管', thirdOrgId: 500, description: '', status: 'ACTIVE' },
        
        // 电话客服组职位
        { positionId: 270, positionName: '电话客服', thirdOrgId: 501, description: '', status: 'ACTIVE' },
        { positionId: 271, positionName: '客服经理', thirdOrgId: 501, description: '', status: 'ACTIVE' },
        
        // 数据挖掘组职位
        { positionId: 280, positionName: '数据挖掘工程师', thirdOrgId: 510, description: '', status: 'ACTIVE' },
        { positionId: 281, positionName: '高级数据挖掘工程师', thirdOrgId: 510, description: '', status: 'ACTIVE' },
        
        // 商业分析组职位
        { positionId: 290, positionName: '商业分析师', thirdOrgId: 511, description: '', status: 'ACTIVE' },
        { positionId: 291, positionName: '高级商业分析师', thirdOrgId: 511, description: '', status: 'ACTIVE' },
        { positionId: 292, positionName: '数据分析经理', thirdOrgId: 511, description: '', status: 'ACTIVE' }
    ],
    salaryItems: [
        { itemId: 1, itemCode: 'S001', itemName: '基本工资', itemType: 'INCOME', calculationRule: null, sortOrder: 1, status: 'ACTIVE' },
        { itemId: 2, itemCode: 'S002', itemName: '绩效奖金', itemType: 'INCOME', calculationRule: null, sortOrder: 2, status: 'ACTIVE' },
        { itemId: 3, itemCode: 'S003', itemName: '交通补贴', itemType: 'INCOME', calculationRule: null, sortOrder: 3, status: 'ACTIVE' },
        { itemId: 4, itemCode: 'S004', itemName: '餐费补贴', itemType: 'INCOME', calculationRule: null, sortOrder: 4, status: 'ACTIVE' },
        { itemId: 5, itemCode: 'S005', itemName: '全勤奖', itemType: 'INCOME', calculationRule: null, sortOrder: 5, status: 'ACTIVE' },
        { itemId: 6, itemCode: 'S006', itemName: '养老保险', itemType: 'DEDUCTION', calculationRule: '基本工资*8%', sortOrder: 6, status: 'ACTIVE' },
        { itemId: 7, itemCode: 'S007', itemName: '医疗保险', itemType: 'DEDUCTION', calculationRule: '基本工资*2%+3', sortOrder: 7, status: 'ACTIVE' },
        { itemId: 8, itemCode: 'S008', itemName: '失业保险', itemType: 'DEDUCTION', calculationRule: '基本工资*0.5%', sortOrder: 8, status: 'ACTIVE' },
        { itemId: 9, itemCode: 'S009', itemName: '住房公积金', itemType: 'DEDUCTION', calculationRule: '基本工资*8%', sortOrder: 9, status: 'ACTIVE' }
    ],
    employeeArchives: [
        {
            archiveId: 1,
            archiveNumber: '20250101010101',
            name: '张明',
            gender: 'MALE',
            idNumber: '110101199001011234',
            birthday: '1990-01-01',
            age: 34,
            nationality: '中国',
            placeOfBirth: '北京',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '计算机科学与技术',
            email: 'zhangming@example.com',
            phone: '010-12345678',
            qq: '123456789',
            mobile: '13800138000',
            address: '北京市朝阳区xxx',
            postalCode: '100000',
            hobby: '阅读、编程',
            personalResume: '2010-2014 就读于XX大学计算机系',
            familyRelationship: '父亲：张XX，母亲：李XX',
            remarks: '技术能力强',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 3,
            secondOrgName: '产品研发部',
            thirdOrgId: 6,
            thirdOrgName: '前端组',
            orgFullPath: '技术中心/产品研发部/前端组',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: 1,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-15T09:30:00',
            reviewerId: 3,
            reviewerName: '李管理员',
            reviewTime: '2025-01-15T10:00:00',
            reviewComments: '审核通过，信息无误',
            status: 'NORMAL'
        },
        {
            archiveId: 2,
            archiveNumber: '20250101010201',
            name: '李华',
            gender: 'MALE',
            idNumber: '110101199205151234',
            birthday: '1992-05-15',
            age: 32,
            nationality: '中国',
            placeOfBirth: '上海',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '团员',
            educationLevel: '本科',
            major: '软件工程',
            email: 'lihua@example.com',
            phone: '021-87654321',
            qq: '987654321',
            mobile: '13900139000',
            address: '上海市浦东新区xxx',
            postalCode: '200000',
            hobby: '运动、音乐',
            personalResume: '2012-2016 就读于XX大学软件工程系',
            familyRelationship: '父亲：李XX，母亲：王XX',
            remarks: '',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 3,
            secondOrgName: '产品研发部',
            thirdOrgId: 7,
            thirdOrgName: '后端组',
            orgFullPath: '技术中心/产品研发部/后端组',
            positionId: 2,
            positionName: '后端工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: 2,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-14T14:20:00',
            reviewerId: 3,
            reviewerName: '李管理员',
            reviewTime: '2025-01-14T15:00:00',
            reviewComments: '审核通过',
            status: 'NORMAL'
        },
        {
            archiveId: 3,
            archiveNumber: '20250101010301',
            name: '王芳',
            gender: 'FEMALE',
            idNumber: '110101199308201234',
            birthday: '1993-08-20',
            age: 31,
            nationality: '中国',
            placeOfBirth: '广州',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '信息管理与信息系统',
            email: 'wangfang@example.com',
            phone: '020-12345678',
            qq: '111222333',
            mobile: '13700137000',
            address: '广州市天河区xxx',
            postalCode: '510000',
            hobby: '旅游、摄影',
            personalResume: '2013-2017 就读于XX大学信息管理系',
            familyRelationship: '父亲：王XX，母亲：赵XX',
            remarks: '',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 4,
            secondOrgName: '测试部',
            thirdOrgId: 9,
            thirdOrgName: '测试一组',
            orgFullPath: '技术中心/测试部/测试一组',
            positionId: 4,
            positionName: '测试工程师',
            jobTitle: 'JUNIOR',
            salaryStandardId: 3,
            registrarId: 3,
            registrarName: '李管理员',
            registrationTime: '2025-01-13T11:05:00',
            reviewerId: 3,
            reviewerName: '李管理员',
            reviewTime: '2025-01-13T11:30:00',
            reviewComments: '审核通过',
            status: 'NORMAL'
        },
        {
            archiveId: 4,
            archiveNumber: '20250101020101',
            name: '赵敏',
            gender: 'FEMALE',
            idNumber: '110101199401151234',
            birthday: '1994-01-15',
            age: 30,
            nationality: '中国',
            placeOfBirth: '深圳',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '党员',
            educationLevel: '硕士',
            major: '产品设计',
            email: 'zhaomin@example.com',
            phone: '0755-12345678',
            qq: '222333444',
            mobile: '13600136000',
            address: '深圳市南山区xxx',
            postalCode: '518000',
            hobby: '设计、阅读',
            personalResume: '2014-2018 就读于XX大学设计系，2018-2020 就读于XX大学研究生',
            familyRelationship: '父亲：赵XX，母亲：钱XX',
            remarks: '有丰富的产品设计经验',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 10,
            secondOrgName: '产品研发部',
            thirdOrgId: 103,
            thirdOrgName: '产品组',
            orgFullPath: '技术中心/产品研发部/产品组',
            positionId: 3,
            positionName: '产品经理',
            jobTitle: 'SENIOR',
            salaryStandardId: 4,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-16T10:00:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 7,
            archiveNumber: '20250101010102',
            name: '陈伟',
            gender: 'MALE',
            idNumber: '110101199506201234',
            birthday: '1995-06-20',
            age: 29,
            nationality: '中国',
            placeOfBirth: '杭州',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '团员',
            educationLevel: '本科',
            major: '计算机科学与技术',
            email: 'chenwei@example.com',
            phone: '0571-12345678',
            qq: '555666777',
            mobile: '13500135001',
            address: '杭州市西湖区xxx',
            postalCode: '310000',
            hobby: '编程、游戏',
            personalResume: '2013-2017 就读于XX大学计算机系',
            familyRelationship: '父亲：陈XX，母亲：周XX',
            remarks: '技术能力突出',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 10,
            secondOrgName: '产品研发部',
            thirdOrgId: 100,
            thirdOrgName: '前端组',
            orgFullPath: '技术中心/产品研发部/前端组',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: 1,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-17T09:15:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 8,
            archiveNumber: '20250101010202',
            name: '刘静',
            gender: 'FEMALE',
            idNumber: '110101199608251234',
            birthday: '1996-08-25',
            age: 28,
            nationality: '中国',
            placeOfBirth: '成都',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '软件工程',
            email: 'liujing@example.com',
            phone: '028-12345678',
            qq: '666777888',
            mobile: '13400134001',
            address: '成都市锦江区xxx',
            postalCode: '610000',
            hobby: '阅读、电影',
            personalResume: '2014-2018 就读于XX大学软件工程系',
            familyRelationship: '父亲：刘XX，母亲：吴XX',
            remarks: '',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 10,
            secondOrgName: '产品研发部',
            thirdOrgId: 101,
            thirdOrgName: '后端组',
            orgFullPath: '技术中心/产品研发部/后端组',
            positionId: 10,
            positionName: '后端工程师',
            jobTitle: 'JUNIOR',
            salaryStandardId: 2,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-17T14:30:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 9,
            archiveNumber: '20250102010102',
            name: '孙磊',
            gender: 'MALE',
            idNumber: '110101199303101234',
            birthday: '1993-03-10',
            age: 31,
            nationality: '中国',
            placeOfBirth: '武汉',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '党员',
            educationLevel: '硕士',
            major: '测试工程',
            email: 'sunlei@example.com',
            phone: '027-12345678',
            qq: '777888999',
            mobile: '13300133001',
            address: '武汉市洪山区xxx',
            postalCode: '430000',
            hobby: '运动、旅游',
            personalResume: '2011-2015 就读于XX大学计算机系，2015-2018 就读于XX大学研究生',
            familyRelationship: '父亲：孙XX，母亲：郑XX',
            remarks: '有丰富的测试经验',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 11,
            secondOrgName: '测试部',
            thirdOrgId: 110,
            thirdOrgName: '功能测试组',
            orgFullPath: '技术中心/测试部/功能测试组',
            positionId: 40,
            positionName: '测试工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: 3,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-18T10:20:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 10,
            archiveNumber: '20250102010202',
            name: '周婷',
            gender: 'FEMALE',
            idNumber: '110101199407151234',
            birthday: '1994-07-15',
            age: 30,
            nationality: '中国',
            placeOfBirth: '南京',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '团员',
            educationLevel: '本科',
            major: '信息管理与信息系统',
            email: 'zhouting@example.com',
            phone: '025-12345678',
            qq: '888999000',
            mobile: '13200132001',
            address: '南京市鼓楼区xxx',
            postalCode: '210000',
            hobby: '音乐、绘画',
            personalResume: '2012-2016 就读于XX大学信息管理系',
            familyRelationship: '父亲：周XX，母亲：王XX',
            remarks: '',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 11,
            secondOrgName: '测试部',
            thirdOrgId: 111,
            thirdOrgName: '自动化测试组',
            orgFullPath: '技术中心/测试部/自动化测试组',
            positionId: 50,
            positionName: '自动化测试工程师',
            jobTitle: 'JUNIOR',
            salaryStandardId: 3,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-18T15:45:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 11,
            archiveNumber: '20250104010102',
            name: '吴强',
            gender: 'MALE',
            idNumber: '110101199211201234',
            birthday: '1992-11-20',
            age: 32,
            nationality: '中国',
            placeOfBirth: '西安',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '网络工程',
            email: 'wuqiang@example.com',
            phone: '029-12345678',
            qq: '999000111',
            mobile: '13100131001',
            address: '西安市雁塔区xxx',
            postalCode: '710000',
            hobby: '摄影、旅行',
            personalResume: '2010-2014 就读于XX大学网络工程系',
            familyRelationship: '父亲：吴XX，母亲：冯XX',
            remarks: '有丰富的运维经验',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 13,
            secondOrgName: '运维部',
            thirdOrgId: 130,
            thirdOrgName: '系统运维组',
            orgFullPath: '技术中心/运维部/系统运维组',
            positionId: 90,
            positionName: '运维工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: 9,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-19T11:00:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 12,
            archiveNumber: '20250502010102',
            name: '郑丽',
            gender: 'FEMALE',
            idNumber: '110101199509051234',
            birthday: '1995-09-05',
            age: 29,
            nationality: '中国',
            placeOfBirth: '重庆',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '团员',
            educationLevel: '本科',
            major: '数据科学与大数据技术',
            email: 'zhengli@example.com',
            phone: '023-12345678',
            qq: '000111222',
            mobile: '13000130001',
            address: '重庆市渝中区xxx',
            postalCode: '400000',
            hobby: '数据分析、阅读',
            personalResume: '2013-2017 就读于XX大学数据科学系',
            familyRelationship: '父亲：郑XX，母亲：陈XX',
            remarks: '擅长数据分析',
            firstOrgId: 5,
            firstOrgName: '运营中心',
            secondOrgId: 51,
            secondOrgName: '数据分析部',
            thirdOrgId: 510,
            thirdOrgName: '数据挖掘组',
            orgFullPath: '运营中心/数据分析部/数据挖掘组',
            positionId: 280,
            positionName: '数据挖掘工程师',
            jobTitle: 'JUNIOR',
            salaryStandardId: null,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-19T16:20:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 13,
            archiveNumber: '20250101010402',
            name: '冯军',
            gender: 'MALE',
            idNumber: '110101199401201234',
            birthday: '1994-01-20',
            age: 30,
            nationality: '中国',
            placeOfBirth: '天津',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '党员',
            educationLevel: '硕士',
            major: '算法工程',
            email: 'fengjun@example.com',
            phone: '022-12345678',
            qq: '111222333',
            mobile: '13900139001',
            address: '天津市南开区xxx',
            postalCode: '300000',
            hobby: '算法研究、编程',
            personalResume: '2012-2016 就读于XX大学计算机系，2016-2019 就读于XX大学研究生',
            familyRelationship: '父亲：冯XX，母亲：褚XX',
            remarks: '算法能力强',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 10,
            secondOrgName: '产品研发部',
            thirdOrgId: 103,
            thirdOrgName: '算法组',
            orgFullPath: '技术中心/产品研发部/算法组',
            positionId: 30,
            positionName: '算法工程师',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: null,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2025-01-20T09:30:00',
            status: 'PENDING_REVIEW'
        },
        {
            archiveId: 5,
            archiveNumber: '20200101010101',
            name: '王强',
            gender: 'MALE',
            idNumber: '110101198801011234',
            birthday: '1988-01-01',
            age: 36,
            nationality: '中国',
            placeOfBirth: '北京',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '计算机科学',
            email: 'wangqiang@example.com',
            phone: '010-11111111',
            qq: '333444555',
            mobile: '13500135000',
            address: '北京市海淀区xxx',
            postalCode: '100000',
            hobby: '',
            personalResume: '',
            familyRelationship: '',
            remarks: '',
            firstOrgId: 1,
            firstOrgName: '技术中心',
            secondOrgId: 3,
            secondOrgName: '产品研发部',
            thirdOrgId: 6,
            thirdOrgName: '前端组',
            orgFullPath: '技术中心/产品研发部/前端组',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'SENIOR',
            salaryStandardId: 5,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2020-01-01T09:00:00',
            reviewerId: 3,
            reviewerName: '李管理员',
            reviewTime: '2020-01-01T10:00:00',
            reviewComments: '审核通过',
            status: 'DELETED',
            deleteTime: '2023-05-20T16:45:00',
            deleteReason: '员工离职'
        },
        {
            archiveId: 6,
            archiveNumber: '20190101010101',
            name: '赵敏',
            gender: 'FEMALE',
            idNumber: '110101199001151234',
            birthday: '1990-01-15',
            age: 34,
            nationality: '中国',
            placeOfBirth: '上海',
            ethnicity: '汉族',
            religiousBelief: '无',
            politicalStatus: '群众',
            educationLevel: '本科',
            major: '市场营销',
            email: 'zhaomin2@example.com',
            phone: '021-22222222',
            qq: '444555666',
            mobile: '13400134000',
            address: '上海市黄浦区xxx',
            postalCode: '200000',
            hobby: '',
            personalResume: '',
            familyRelationship: '',
            remarks: '',
            firstOrgId: 2,
            firstOrgName: '市场中心',
            secondOrgId: 5,
            secondOrgName: '市场推广部',
            thirdOrgId: null,
            thirdOrgName: '',
            orgFullPath: '市场中心/市场推广部',
            positionId: null,
            positionName: '',
            jobTitle: 'INTERMEDIATE',
            salaryStandardId: null,
            registrarId: 2,
            registrarName: '王管理员',
            registrationTime: '2019-01-01T09:00:00',
            reviewerId: 3,
            reviewerName: '李管理员',
            reviewTime: '2019-01-01T10:00:00',
            reviewComments: '审核通过',
            status: 'DELETED',
            deleteTime: '2023-04-10T11:20:00',
            deleteReason: '员工离职'
        }
    ],
    salaryStandards: [
        {
            standardId: 1,
            standardCode: 'SAL202501001',
            standardName: '前端工程师-中级标准',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-10T09:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-10T14:30:00',
            reviewComments: '审核通过，标准合理',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 12000, isCalculated: false },
                { itemId: 2, amount: 3000, isCalculated: false },
                { itemId: 3, amount: 500, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 6, amount: 960, isCalculated: true },
                { itemId: 7, amount: 243, isCalculated: true },
                { itemId: 8, amount: 60, isCalculated: true },
                { itemId: 9, amount: 960, isCalculated: true }
            ]
        },
        {
            standardId: 2,
            standardCode: 'SAL202501002',
            standardName: '高级前端工程师-中级标准',
            positionId: 2,
            positionName: '高级前端工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-11T10:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-11T15:00:00',
            reviewComments: '审核通过',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 13000, isCalculated: false },
                { itemId: 2, amount: 3500, isCalculated: false },
                { itemId: 3, amount: 500, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 6, amount: 1040, isCalculated: true },
                { itemId: 7, amount: 263, isCalculated: true },
                { itemId: 8, amount: 65, isCalculated: true },
                { itemId: 9, amount: 1040, isCalculated: true }
            ]
        },
        {
            standardId: 3,
            standardCode: 'SAL202501003',
            standardName: '前端开发经理-初级标准',
            positionId: 4,
            positionName: '前端开发经理',
            jobTitle: 'JUNIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-12T09:30:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-12T16:00:00',
            reviewComments: '审核通过',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 8000, isCalculated: false },
                { itemId: 2, amount: 1500, isCalculated: false },
                { itemId: 3, amount: 300, isCalculated: false },
                { itemId: 4, amount: 200, isCalculated: false },
                { itemId: 6, amount: 640, isCalculated: true },
                { itemId: 7, amount: 163, isCalculated: true },
                { itemId: 8, amount: 40, isCalculated: true },
                { itemId: 9, amount: 640, isCalculated: true }
            ]
        },
        {
            standardId: 4,
            standardCode: 'SAL202501004',
            standardName: '前端架构师-高级标准',
            positionId: 3,
            positionName: '前端架构师',
            jobTitle: 'SENIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-13T10:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-13T14:00:00',
            reviewComments: '审核通过',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 18000, isCalculated: false },
                { itemId: 2, amount: 5000, isCalculated: false },
                { itemId: 3, amount: 800, isCalculated: false },
                { itemId: 4, amount: 500, isCalculated: false },
                { itemId: 6, amount: 1440, isCalculated: true },
                { itemId: 7, amount: 363, isCalculated: true },
                { itemId: 8, amount: 90, isCalculated: true },
                { itemId: 9, amount: 1440, isCalculated: true }
            ]
        },
        {
            standardId: 5,
            standardCode: 'SAL202001001',
            standardName: '前端工程师-高级标准',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'SENIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2020-01-01T09:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2020-01-01T10:00:00',
            reviewComments: '审核通过',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 15000, isCalculated: false },
                { itemId: 2, amount: 4000, isCalculated: false },
                { itemId: 3, amount: 600, isCalculated: false },
                { itemId: 4, amount: 400, isCalculated: false },
                { itemId: 6, amount: 1200, isCalculated: true },
                { itemId: 7, amount: 303, isCalculated: true },
                { itemId: 8, amount: 75, isCalculated: true },
                { itemId: 9, amount: 1200, isCalculated: true }
            ]
        },
        {
            standardId: 6,
            standardCode: 'SAL202501005',
            standardName: '前端工程师-初级标准',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'JUNIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-15T09:00:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 9000, isCalculated: false },
                { itemId: 2, amount: 2000, isCalculated: false },
                { itemId: 3, amount: 400, isCalculated: false },
                { itemId: 4, amount: 250, isCalculated: false },
                { itemId: 6, amount: 720, isCalculated: true },
                { itemId: 7, amount: 183, isCalculated: true },
                { itemId: 8, amount: 45, isCalculated: true },
                { itemId: 9, amount: 720, isCalculated: true }
            ]
        },
        {
            standardId: 7,
            standardCode: 'SAL202501006',
            standardName: '后端工程师-高级标准',
            positionId: 10,
            positionName: '后端工程师',
            jobTitle: 'SENIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-14T11:00:00',
            reviewerId: null,
            reviewerName: null,
            reviewTime: null,
            reviewComments: '标准金额过高，需要调整',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 20000, isCalculated: false },
                { itemId: 2, amount: 6000, isCalculated: false },
                { itemId: 3, amount: 1000, isCalculated: false },
                { itemId: 4, amount: 600, isCalculated: false },
                { itemId: 6, amount: 1600, isCalculated: true },
                { itemId: 7, amount: 403, isCalculated: true },
                { itemId: 8, amount: 100, isCalculated: true },
                { itemId: 9, amount: 1600, isCalculated: true }
            ]
        },
        {
            standardId: 8,
            standardCode: 'SAL202501007',
            standardName: '高级前端工程师-中级标准',
            positionId: 2,
            positionName: '高级前端工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-16T10:30:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 11000, isCalculated: false },
                { itemId: 2, amount: 2500, isCalculated: false },
                { itemId: 3, amount: 400, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 6, amount: 880, isCalculated: true },
                { itemId: 7, amount: 223, isCalculated: true },
                { itemId: 8, amount: 55, isCalculated: true },
                { itemId: 9, amount: 880, isCalculated: true }
            ]
        },
        {
            standardId: 9,
            standardCode: 'SAL202501008',
            standardName: '运维工程师-中级标准',
            positionId: 90,
            positionName: '运维工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-17T09:15:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-17T15:20:00',
            reviewComments: '标准合理，审核通过',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 12500, isCalculated: false },
                { itemId: 2, amount: 3200, isCalculated: false },
                { itemId: 3, amount: 500, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 6, amount: 1000, isCalculated: true },
                { itemId: 7, amount: 253, isCalculated: true },
                { itemId: 8, amount: 62.5, isCalculated: true },
                { itemId: 9, amount: 1000, isCalculated: true }
            ]
        },
        {
            standardId: 10,
            standardCode: 'SAL202501009',
            standardName: '算法工程师-初级标准',
            positionId: 30,
            positionName: '算法工程师',
            jobTitle: 'JUNIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-18T11:00:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 8500, isCalculated: false },
                { itemId: 2, amount: 1800, isCalculated: false },
                { itemId: 3, amount: 350, isCalculated: false },
                { itemId: 4, amount: 250, isCalculated: false },
                { itemId: 6, amount: 680, isCalculated: true },
                { itemId: 7, amount: 173, isCalculated: true },
                { itemId: 8, amount: 42.5, isCalculated: true },
                { itemId: 9, amount: 680, isCalculated: true }
            ]
        },
        {
            standardId: 11,
            standardCode: 'SAL202501010',
            standardName: '前端架构师-高级标准',
            positionId: 3,
            positionName: '前端架构师',
            jobTitle: 'SENIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-19T10:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2025-01-19T16:30:00',
            reviewComments: '审核通过，标准符合市场水平',
            status: 'APPROVED',
            items: [
                { itemId: 1, amount: 20000, isCalculated: false },
                { itemId: 2, amount: 6000, isCalculated: false },
                { itemId: 3, amount: 1000, isCalculated: false },
                { itemId: 4, amount: 600, isCalculated: false },
                { itemId: 6, amount: 1600, isCalculated: true },
                { itemId: 7, amount: 403, isCalculated: true },
                { itemId: 8, amount: 100, isCalculated: true },
                { itemId: 9, amount: 1600, isCalculated: true }
            ]
        },
        {
            standardId: 12,
            standardCode: 'SAL202501011',
            standardName: 'iOS开发工程师-中级标准',
            positionId: 20,
            positionName: 'iOS开发工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-20T09:30:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 11500, isCalculated: false },
                { itemId: 2, amount: 2800, isCalculated: false },
                { itemId: 3, amount: 450, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 6, amount: 920, isCalculated: true },
                { itemId: 7, amount: 233, isCalculated: true },
                { itemId: 8, amount: 57.5, isCalculated: true },
                { itemId: 9, amount: 920, isCalculated: true }
            ]
        },
        {
            standardId: 13,
            standardCode: 'SAL202511001',
            standardName: '前端工程师-初级标准',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'JUNIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T09:00:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 8000, isCalculated: false },
                { itemId: 2, amount: 2000, isCalculated: false },
                { itemId: 3, amount: 500, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 5, amount: 200, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        },
        {
            standardId: 14,
            standardCode: 'SAL202511002',
            standardName: '前端工程师-中级标准',
            positionId: 1,
            positionName: '前端工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T09:15:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 12000, isCalculated: false },
                { itemId: 2, amount: 3000, isCalculated: false },
                { itemId: 3, amount: 800, isCalculated: false },
                { itemId: 4, amount: 500, isCalculated: false },
                { itemId: 5, amount: 300, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        },
        {
            standardId: 15,
            standardCode: 'SAL202511003',
            standardName: '后端工程师-中级标准',
            positionId: 10,
            positionName: '后端工程师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T09:30:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 13000, isCalculated: false },
                { itemId: 2, amount: 3500, isCalculated: false },
                { itemId: 3, amount: 800, isCalculated: false },
                { itemId: 4, amount: 500, isCalculated: false },
                { itemId: 5, amount: 300, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        },
        {
            standardId: 16,
            standardCode: 'SAL202511004',
            standardName: '后端工程师-高级标准',
            positionId: 10,
            positionName: '后端工程师',
            jobTitle: 'SENIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T09:45:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 18000, isCalculated: false },
                { itemId: 2, amount: 5000, isCalculated: false },
                { itemId: 3, amount: 1000, isCalculated: false },
                { itemId: 4, amount: 600, isCalculated: false },
                { itemId: 5, amount: 500, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        },
        {
            standardId: 17,
            standardCode: 'SAL202511005',
            standardName: '产品经理-中级标准',
            positionId: 3,
            positionName: '前端架构师',
            jobTitle: 'INTERMEDIATE',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T10:00:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 15000, isCalculated: false },
                { itemId: 2, amount: 4000, isCalculated: false },
                { itemId: 3, amount: 800, isCalculated: false },
                { itemId: 4, amount: 500, isCalculated: false },
                { itemId: 5, amount: 400, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        },
        {
            standardId: 18,
            standardCode: 'SAL202511006',
            standardName: '测试工程师-初级标准',
            positionId: 40,
            positionName: '测试工程师',
            jobTitle: 'JUNIOR',
            formulatorId: 4,
            formulatorName: '薪酬专员',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-11-15T10:15:00',
            status: 'PENDING_REVIEW',
            items: [
                { itemId: 1, amount: 7500, isCalculated: false },
                { itemId: 2, amount: 1500, isCalculated: false },
                { itemId: 3, amount: 400, isCalculated: false },
                { itemId: 4, amount: 300, isCalculated: false },
                { itemId: 5, amount: 200, isCalculated: false },
                { itemId: 6, amount: 0, isCalculated: true },
                { itemId: 7, amount: 0, isCalculated: true },
                { itemId: 8, amount: 0, isCalculated: true },
                { itemId: 9, amount: 0, isCalculated: true }
            ]
        }
    ],
    salaryIssuances: [
        {
            issuanceId: 1,
            salarySlipNumber: 'PAY202307001',
            thirdOrgId: 100,
            thirdOrgName: '前端组',
            orgFullPath: '技术中心/产品研发部/前端组',
            totalEmployees: 15,
            totalBasicSalary: 180000.00,
            totalNetPay: 165000.00,
            issuanceMonth: '2023-07-01',
            issuanceTime: '2023-07-15',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2023-07-10T09:30:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2023-07-12T14:00:00',
            status: 'EXECUTED',
            paymentStatus: 'PAID'
        },
        {
            issuanceId: 2,
            salarySlipNumber: 'PAY202306001',
            thirdOrgId: 101,
            thirdOrgName: '后端组',
            orgFullPath: '技术中心/产品研发部/后端组',
            totalEmployees: 20,
            totalBasicSalary: 240000.00,
            totalNetPay: 220000.00,
            issuanceMonth: '2023-06-01',
            issuanceTime: '2023-06-15',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2023-06-10T09:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2023-06-12T15:00:00',
            status: 'EXECUTED',
            paymentStatus: 'PAID'
        },
        {
            issuanceId: 3,
            salarySlipNumber: 'PAY202305001',
            thirdOrgId: 110,
            thirdOrgName: '功能测试组',
            orgFullPath: '技术中心/测试部/功能测试组',
            totalEmployees: 8,
            totalBasicSalary: 96000.00,
            totalNetPay: 88000.00,
            issuanceMonth: '2023-05-01',
            issuanceTime: '2023-05-15',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2023-05-10T10:00:00',
            reviewerId: 5,
            reviewerName: '薪酬经理',
            reviewTime: '2023-05-12T14:30:00',
            status: 'EXECUTED',
            paymentStatus: 'PAID'
        },
        {
            issuanceId: 4,
            salarySlipNumber: 'PAY202501001',
            thirdOrgId: 100,
            thirdOrgName: '前端组',
            orgFullPath: '技术中心/产品研发部/前端组',
            totalEmployees: 15,
            totalBasicSalary: 180000.00,
            totalNetPay: 165000.00,
            issuanceMonth: '2025-01-01',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-15T09:00:00',
            status: 'PENDING_REVIEW',
            paymentStatus: null
        },
        {
            issuanceId: 5,
            salarySlipNumber: 'PAY202501002',
            thirdOrgId: 101,
            thirdOrgName: '后端组',
            orgFullPath: '技术中心/产品研发部/后端组',
            totalEmployees: 20,
            totalBasicSalary: 240000.00,
            totalNetPay: 220000.00,
            issuanceMonth: '2025-01-01',
            registrarId: 4,
            registrarName: '薪酬专员',
            registrationTime: '2025-01-16T10:00:00',
            status: 'PENDING_REGISTRATION',
            paymentStatus: null
        }
    ],
    salaryIssuanceDetails: [
        // 第一个发放单的明细（15个员工）
        ...Array.from({ length: 15 }, (_, i) => ({
            detailId: i + 1,
            issuanceId: 1,
            employeeId: i + 1,
            employeeNumber: `2023010101010${String(i + 1).padStart(2, '0')}`,
            employeeName: `员工${i + 1}`,
            positionName: '前端工程师',
            basicSalary: 12000.00,
            performanceBonus: 2000.00,
            transportationAllowance: 500.00,
            mealAllowance: 300.00,
            pensionInsurance: 960.00,
            medicalInsurance: 243.00,
            unemploymentInsurance: 60.00,
            housingFund: 960.00,
            awardAmount: i < 3 ? 500.00 : 0.00,
            deductionAmount: 0.00,
            totalIncome: 12000 + 2000 + 500 + 300 + (i < 3 ? 500 : 0),
            totalDeduction: 960 + 243 + 60 + 960,
            netPay: (12000 + 2000 + 500 + 300 + (i < 3 ? 500 : 0)) - (960 + 243 + 60 + 960)
        })),
        // 第二个发放单的明细（20个员工）
        ...Array.from({ length: 20 }, (_, i) => ({
            detailId: 16 + i,
            issuanceId: 2,
            employeeId: 16 + i,
            employeeNumber: `2023010101020${String(i + 1).padStart(2, '0')}`,
            employeeName: `员工${16 + i}`,
            positionName: '后端工程师',
            basicSalary: 12000.00,
            performanceBonus: 2000.00,
            transportationAllowance: 500.00,
            mealAllowance: 300.00,
            pensionInsurance: 960.00,
            medicalInsurance: 243.00,
            unemploymentInsurance: 60.00,
            housingFund: 960.00,
            awardAmount: i < 5 ? 500.00 : 0.00,
            deductionAmount: 0.00,
            totalIncome: 12000 + 2000 + 500 + 300 + (i < 5 ? 500 : 0),
            totalDeduction: 960 + 243 + 60 + 960,
            netPay: (12000 + 2000 + 500 + 300 + (i < 5 ? 500 : 0)) - (960 + 243 + 60 + 960)
        })),
        // 第三个发放单的明细（8个员工）
        ...Array.from({ length: 8 }, (_, i) => ({
            detailId: 36 + i,
            issuanceId: 3,
            employeeId: 36 + i,
            employeeNumber: `2023010101110${String(i + 1).padStart(2, '0')}`,
            employeeName: `员工${36 + i}`,
            positionName: '测试工程师',
            basicSalary: 12000.00,
            performanceBonus: 1500.00,
            transportationAllowance: 500.00,
            mealAllowance: 300.00,
            pensionInsurance: 960.00,
            medicalInsurance: 243.00,
            unemploymentInsurance: 60.00,
            housingFund: 960.00,
            awardAmount: 0.00,
            deductionAmount: 0.00,
            totalIncome: 12000 + 1500 + 500 + 300,
            totalDeduction: 960 + 243 + 60 + 960,
            netPay: (12000 + 1500 + 500 + 300) - (960 + 243 + 60 + 960)
        })),
        // 第四个发放单的明细（15个员工，待复核）
        ...Array.from({ length: 15 }, (_, i) => ({
            detailId: 44 + i,
            issuanceId: 4,
            employeeId: i + 1,
            employeeNumber: `2023010101010${String(i + 1).padStart(2, '0')}`,
            employeeName: `员工${i + 1}`,
            positionName: '前端工程师',
            basicSalary: 12000.00,
            performanceBonus: 2000.00,
            transportationAllowance: 500.00,
            mealAllowance: 300.00,
            pensionInsurance: 960.00,
            medicalInsurance: 243.00,
            unemploymentInsurance: 60.00,
            housingFund: 960.00,
            awardAmount: 0.00,
            deductionAmount: 0.00,
            totalIncome: 12000 + 2000 + 500 + 300,
            totalDeduction: 960 + 243 + 60 + 960,
            netPay: (12000 + 2000 + 500 + 300) - (960 + 243 + 60 + 960)
        }))
    ],
    nextOrgId: 10,
    nextPositionId: 5,
    nextSalaryItemId: 10,
    nextArchiveId: 14,
    nextStandardId: 19,
    nextIssuanceId: 6,
    nextIssuanceDetailId: 60
};

// 从localStorage加载数据
function loadMockData() {
    const saved = localStorage.getItem('mockHRData');
    if (saved) {
        const savedData = JSON.parse(saved);
        // 合并数据，但保留初始的假数据（如果localStorage中没有对应数据）
        if (!savedData.employeeArchives || savedData.employeeArchives.length === 0) {
            // 如果localStorage中没有员工档案数据，使用初始假数据
            savedData.employeeArchives = MockData.employeeArchives;
        } else {
            // 合并员工档案数据：保留localStorage中的数据，但添加新的待复核数据（如果不存在）
            const existingIds = new Set(savedData.employeeArchives.map(a => a.archiveId));
            const newArchives = MockData.employeeArchives.filter(a => !existingIds.has(a.archiveId));
            savedData.employeeArchives = [...savedData.employeeArchives, ...newArchives];
            // 更新nextArchiveId
            if (savedData.nextArchiveId < MockData.nextArchiveId) {
                savedData.nextArchiveId = MockData.nextArchiveId;
            }
        }
        if (!savedData.salaryStandards || savedData.salaryStandards.length === 0) {
            // 如果localStorage中没有薪酬标准数据，使用初始假数据
            savedData.salaryStandards = MockData.salaryStandards;
        } else {
            // 合并薪酬标准数据：保留localStorage中的数据，但添加新的待复核数据（如果不存在）
            const existingIds = new Set(savedData.salaryStandards.map(s => s.standardId));
            const newStandards = MockData.salaryStandards.filter(s => !existingIds.has(s.standardId));
            savedData.salaryStandards = [...savedData.salaryStandards, ...newStandards];
            // 更新nextStandardId
            if (savedData.nextStandardId < MockData.nextStandardId) {
                savedData.nextStandardId = MockData.nextStandardId;
            }
        }
        if (!savedData.salaryIssuances || savedData.salaryIssuances.length === 0) {
            // 如果localStorage中没有薪酬发放数据，使用初始假数据
            savedData.salaryIssuances = MockData.salaryIssuances;
        }
        if (!savedData.salaryIssuanceDetails || savedData.salaryIssuanceDetails.length === 0) {
            // 如果localStorage中没有薪酬发放明细数据，使用初始假数据
            savedData.salaryIssuanceDetails = MockData.salaryIssuanceDetails;
        }
        Object.assign(MockData, savedData);
    }
    // 如果localStorage中没有数据，使用初始假数据（已经在MockData中定义）
}

// 保存数据到localStorage
function saveMockData() {
    localStorage.setItem('mockHRData', JSON.stringify(MockData));
}

// 初始化加载
loadMockData();

